version: '2'
services:
  apache:
    build: ./apache
    container_name: apache
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - php56
    volumes:
      - ./apps:/usr/local/apache2/htdocs
      - ./apache/logs:/usr/local/apache2/logs
      - ./apache/conf/vhosts:/usr/local/apache2/conf/vhosts

  php56:
    build: ./php56/fpm
    container_name: php56
    restart: always
    ports:
      - "9000:9000"
    links:
      - mysql
    volumes:
      - ./apps:/usr/local/apache2/htdocs

  php56-cli:
    build: ./php56/cli
    container_name: php56-cli
    volumes_from:
      - php56
    links:
      - mysql

  mysql:
    image: mysql:5.6
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
     - PMA_ARBITRARY=1
     - PMA_USER=root
     - PMA_PASSWORD=root
     - PMA_HOST=mysql
    links:
      - mysql
    ports:
     - "8080:80"